# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-_9oZFnv_VRudCm6rhMopR_ZsbfoEuM
"""

from pyhealth.medcode import CrossMap, InnerMap
import pandas as pd

# mapping = CrossMap.load(source_vocabulary="ICD9CM", target_vocabulary="CCSCM")
# mapping.map("428.0")

icd9cm = InnerMap.load("ICD9CM")
icd9cm.get_ancestors("392")

# Define the file path
file_path = "/content/D_ICD_DIAGNOSES.csv"

# Read the CSV file
data = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(data.head())

icd9cm = InnerMap.load("ICD9CM")
ancestors = [j for i in data['ICD9_CODE'] for j in icd9cm.get_ancestors(i) if '.' not in j]
data['ancestors'] = pd.Series(ancestors)

data.head()

len(set(ancestors))

ancestors = [icd9cm.get_ancestors(i) for i in data['ICD9_CODE']]
new_code = set()
for i, j in zip(data['ICD9_CODE'], ancestors):
  # print(i)
  # print(j)
  new_code.add(j[0])
len(new_code)

## patient
## patient id (SUBJECT_ID) as unique identifier
## SUBJECT_ID, DOB
## DOB is shifted

## diagnoses_icd
## SUBJECT_ID, HADM_ID as unique identifier
## SUBJECT_ID, HADM_ID, ICD9_CODE

## drgcodes
## SUBJECT_ID, HADM_ID as unique identifier
## SUBJECT_ID, HADM_ID, DRG_CODE

## prescription
## SUBJECT_ID, HADM_ID as unique identifier
## SUBJECT_ID, HADM_ID, FORMULARY_DRUG_CD/NDC
## not sure the difference between prescription and drgcodes

## dictionary
# d_icd_diagnoses